### ISSUE TITLE
java.lang.ClassCastException: 宿主Application cannot be cast to com.tencent.shadow.core.runtime.ShadowApplication

### ISSUE THREAD

**Issue by hzx0910** [Tencent/Shadow#254]
为什么要把宿主Application转化成ShadowApplication

**Comment by shifujun** [comment]
还是没有代码呀。

不过我猜是插件的代码中有获取Context后强制转换成Application的代码。这是业务代码写的不正确，关于这一点可以复习强制类型转换的弊端的相关知识。一般这种情况可以通过使用Context类型或者自定义接口类型来解决，解决了强转，问题就解决了。

**Comment by hzx0910** [comment]
@shifujun 这是我调用的sdk里面的逻辑，这种是很常见的用法呀，没法支持吗

**Comment by Scarlet-Pan** [comment]
Context.getApplicationContext()获取到的Context对象，我们一般认为可以转换为Application才对，虽然Google未曾这样生命方法，但至少历届版本这样的结果值都是正确的。
现在返回值变为了ShadowApplication对象，是否可以认为在插件环境下，语义兼容性存在问题？

**Comment by shifujun** [comment]
我还是觉得这不是对的。你看历届版本的Android中，也都可以override `getApplicationContext`方法返回一个`ContextWrapper`对象。在这种场景下，强制转换成Application类型本身就会失败。所以我认为getApplicationContext后强制转换成Application类型是一种比较常见的编程错误。

Activity和Service上都有`getApplication`方法，可以直接取得Application类型，这个方法在Shadow里是可以正常工作的。其他场景下，应该由自定义的Application类型自定义的提供`getApplication`方法。

**Comment by Scarlet-Pan** [comment]
> 我还是觉得这不是对的。你看历届版本的Android中，也都可以override `getApplicationContext`方法返回一个`ContextWrapper`对象。在这种场景下，强制转换成Application类型本身就会失败。所以我认为getApplicationContext后强制转换成Application类型是一种比较常见的编程错误。
> 
> Activity和Service上都有`getApplication`方法，可以直接取得Application类型，这个方法在Shadow里是可以正常工作的。其他场景下，应该由自定义的Application类型自定义的提供`getApplication`方法。

我赞同你的想法，严格来讲，的确将getApplicationContext()的返回值视为Context会更严谨这是它二进制兼容性所决定的。
但另一方面讲，作为插件框架，应该做的是工程作为App和作为插件运行，其内部实现和业务逻辑应保持语义一致性。即：我们应该期望Fragment.getActivity()所返回的Activity应该是它约定的运行环境中所附着的Activity，例如MainActivity；而不是实际运行的PluginDefaultProxyActivity或是其它什么代理Activity，我相信这一点你是赞同的，虽然getActivity()方法的确仅承诺返回Activity类型的对象。因此，这便是我们区分于二进制兼容性的语义兼容性，就像是我们不应认可Collection.size()方法不应返回小于0的数一样，即便它的实现类确实可以这样做。

此外，更正一个自己的错误，刚刚重新阅读了Context的Java Doc，从语义上来讲，我们应该可以理解为其返回的是一个Application对象：
Added in API level 1
Context getApplicationContext ()
Return the context of the single, global Application object of the current process. This generally should only be used if you need a Context whose lifecycle is separate from the current context, that is tied to the lifetime of the process rather than the current component.

**Comment by shifujun** [comment]
这个Issue的问题还是有点模糊，脱离了代码，讨论的不太实际。

前面说的都是对的，似乎没什么问题。插件作为宿主代码的一部分，它不能直接跟Application类型交互。所以插件中所有Application类型都变成了ShadowApplication。这时，插件内部的代码中强制类型转换成Application的代码也会编程强制类型转换到ShadowApplication类型，所以一般情况下是不会有问题的。

可能的问题在于通过一些非常规手段，插件的代码拿到了宿主的Application对象。这种情况还是根据具体场景来讨论吧。

**Comment by Scarlet-Pan** [comment]
> 这个Issue的问题还是有点模糊，脱离了代码，讨论的不太实际。
> 
> 前面说的都是对的，似乎没什么问题。插件作为宿主代码的一部分，它不能直接跟Application类型交互。所以插件中所有Application类型都变成了ShadowApplication。这时，插件内部的代码中强制类型转换成Application的代码也会编程强制类型转换到ShadowApplication类型，所以一般情况下是不会有问题的。
> 
> 可能的问题在于通过一些非常规手段，插件的代码拿到了宿主的Application对象。这种情况还是根据具体场景来讨论吧。

这个Issue的题主并不是我，所以我不确认他的问题；我这边只是遇到了相似的问题，在非Activity或Service里，例如BroadcastReceiver或是某个底层模块，需要获取Application对象registerActivitiesLifecyclerCallbacks()。这种情况下，我们一般应该可以通过Context.getApplicationContext()来作为Application对象才对。
我仍然建议你们考虑一下这个方法遵照原有返回值进行返回，不论是从语义兼容性角度，还是从Google的API文档来说。

**Comment by shifujun** [comment]
你可以在ShadowContext的实现中看到，现在getApplicationContext 方法返回的就是ShadowApplication对象。所以可以正常强转成ShadowApplication类型，进而调用你需要的registerActivityLifecycleCallbacks方法。

所以，如果你遇到了这种问题，还是要有代码才好说到底是什么问题。

**Comment by shifujun** [comment]
如果还有问题，请参考
https://github.com/Tencent/Shadow/blob/dev/CONTRIBUTING.md#issue
再重新打开Issue。
